// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiDjx2fSNiGTLaFUr02F4sPS8m97wXLUk',
    appId: '1:386731480025:web:304554c409932812ddffc8',
    messagingSenderId: '386731480025',
    projectId: 'invisitactoe-dsais-20250910',
    authDomain: 'invisitactoe-dsais-20250910.firebaseapp.com',
    storageBucket: 'invisitactoe-dsais-20250910.firebasestorage.app',
    measurementId: 'G-8F9W6E25QG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw49muIbNNWc-gylGJppIo1QwaiTUArGI',
    appId: '1:386731480025:android:88cfb02c132a3d36ddffc8',
    messagingSenderId: '386731480025',
    projectId: 'invisitactoe-dsais-20250910',
    storageBucket: 'invisitactoe-dsais-20250910.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDxOVHz59xalldKGsL6SrJohX5jboVZ9c',
    appId: '1:386731480025:ios:47ae5ef94d7afa6dddffc8',
    messagingSenderId: '386731480025',
    projectId: 'invisitactoe-dsais-20250910',
    storageBucket: 'invisitactoe-dsais-20250910.firebasestorage.app',
    iosBundleId: 'com.example.invisitactoe',
  );
}
